user  nginx;
worker_processes  auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    client_max_body_size 5G;
    
    sendfile        on;
    keepalive_timeout  65;

    # Сжатие для скорости
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;

    upstream backend_app { server fastapi_backend:8000; }

    # Редирект с HTTP на HTTPS
    server {
        listen 80;
        server_name web-flicker.ru vpn.web-flicker.online;
        return 301 https://$host$request_uri;
    }

    # Основной сайт web-flicker.ru
    server {
        listen 443 ssl;
        http2 on;
        server_name web-flicker.ru;
        ssl_certificate /etc/letsencrypt/live/web-flicker.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/web-flicker.ru/privkey.pem;

        location / {
            proxy_pass http://backend_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }

    # VPN Сервер и Магия ссылки
    server {
        listen 443 ssl;
        http2 on;
        server_name vpn.web-flicker.online;
        ssl_certificate /etc/letsencrypt/live/vpn.web-flicker.online/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/vpn.web-flicker.online/privkey.pem;

        # Механизм редиректа в HAPP
        location /redirect {
            if ($arg_to) { return 302 $arg_to; }
            return 404;
        }

        # Сама панель и страницы подписок
        location / {
            proxy_pass https://172.17.0.1:8080;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # Каналы для обхода блокировок (WS)
        location /vless-ws { proxy_pass http://172.17.0.1:8081; proxy_http_version 1.1; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection "upgrade"; proxy_set_header Host $host; }
        location /trojan-ws { proxy_pass http://172.17.0.1:8082; proxy_http_version 1.1; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection "upgrade"; proxy_set_header Host $host; }
        location /vmess-ws { proxy_pass http://172.17.0.1:8083; proxy_http_version 1.1; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection "upgrade"; proxy_set_header Host $host; }
    }
}
